name: vbart.eventsdemo
services:
- name: monolithicdb
  image: mcr.microsoft.com/mssql/server:latest
  tags:
    - monolithic_db
  bindings:
    - name: Default
      port: 1433
    - name: Connection
      connectionString: Server=${host};Database=Inventory;User Id=sa;Password=YourStrongPassw0rd;Enlist=true;
  env:
  - ACCEPT_EULA=Y
  - SA_PASSWORD=YourStrongPassw0rd
  - MSSQL_AGENT_ENABLED=true

- name: configurator
  dockerFile: Docker/Configurator.Dockerfile
  dockerFileContext: .
  env:
    - SQL_SERVER_HOST=monolithicdb
    - SQL_SERVER_PORT=1433
    - SQL_SERVER_USER=sa
    - SQL_SERVER_PASSWORD=YourStrongPassw0rd
    - SQL_SERVER_DATABASE=Inventory
    - SQL_SERVER_SERVER_NAME=dbServer