name: vbart.eventsdemo
services:
  - name: InventoryApi
    project: src\VBart.EventsDemo.Inventory.Api\VBart.EventsDemo.Inventory.Api.csproj

  - name: DataGen
    project: src\VBart.EventsDemo.Inventory.DataGen\VBart.EventsDemo.Inventory.DataGen.csproj
    args: "--vehicles 15 --wait 1"
    replicas: 2

  - name: InventoryAggregator
    project: src\VBart.EventsDemo.Inventory.Aggregator\VBart.EventsDemo.Inventory.Aggregator.csproj
    env:
      - VEHICLE__KAFKA_CONSUMER_OPTIONS__ConsumerGroupId="aggregator"
      - VEHICLE__KAFKA_CONSUMER_OPTIONS__Topics="dbServer.dbo.Vehicles"
      - VEHICLE__KAFKA_CONSUMER_OPTIONS__BootstrapServers="kafka-broker-2:29094,kafka-broker-1:29092"
      - ENGINE__KAFKA_CONSUMER_OPTIONS__ConsumerGroupId="aggregator"
      - ENGINE__KAFKA_CONSUMER_OPTIONS__Topics="dbServer.dbo.Engines"
      - ENGINE__KAFKA_CONSUMER_OPTIONS__BootstrapServers="kafka-broker-2:29094,kafka-broker-1:29092"
      - KAFKA_PRODUCER_OPTIONS__BootstrapServers="kafka-broker-2:29094,kafka-broker-1:29092"
      - KAFKA_PRODUCER_OPTIONS__AutoCreateTopics=true


  - name: monolithicdb
    image: mcr.microsoft.com/mssql/server:latest
    bindings:
      - name: Default
        port: 1433
      - name: Connection
        connectionString: Server=${host};Database=Inventory;User Id=sa;Password=YourStrongPassw0rd;Enlist=true;
    env:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=YourStrongPassw0rd
    - MSSQL_AGENT_ENABLED=true

  - name: kafka-zookeeper
    image: confluentinc/cp-zookeeper:6.1.0
    bindings:
      - name: zookeeper
        port: 2181
      - name: zookeeper-secure
        port: 2182
    env:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - source: ./data/kafka
        target: /var/lib/kafka/data-z

  - name: kafka-broker-1
    image: confluentinc/cp-kafka:6.1.0
    bindings:
      - name: PlainTextListener
        port: 29092
      - name: PlainTextHostListener
        port: 9092
      - name: Jmx
        port: 9091
    env:
      - KAFKA_ZOOKEEPER_CONNECT="kafka-zookeeper:2181"
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://kafka-broker-1:9092"
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_JMX_PORT=9091
      - KAFKA_JMX_HOSTNAME=kafka-broker-1
    volumes:
      - source: ./data/kafka
        target: /var/lib/kafka/data-1

  - name: kafka-broker-2
    image: confluentinc/cp-kafka:6.1.0
    bindings:
      - name: PlainTextListener
        port: 29094
      - name: PlainTextHostListener
        port: 9094
      - name: Jmx
        port: 9093
    env:
      - KAFKA_ZOOKEEPER_CONNECT="kafka-zookeeper:2181"
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://kafka-broker-2:29094,PLAINTEXT_HOST://kafka-broker-2:9094"
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_JMX_PORT=9093
      - KAFKA_JMX_HOSTNAME=kafka-broker-2
    volumes:
      - source: ./data/kafka
        target: /var/lib/kafka/data-2

  - name: confluent-control-center
    image: confluentinc/cp-enterprise-control-center:5.5.0
    bindings:
      - protocol: http
        port: 9021
        containerPort: 9021
    env:
      - CONTROL_CENTER_BOOTSTRAP_SERVERS="kafka-broker-1:29092,kafka-broker-2:29094"
      - CONTROL_CENTER_ZOOKEEPER_CONNECT="kafka-zookeeper:2181"
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1
      - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1
      - CONFLUENT_METRICS_TOPIC_REPLICATION=1
      - PORT=9021
      - CONTROL_CENTER_CONNECT_CLUSTER="http://kafka-connect:8083/"

  - name: kafka-connect
    image: debezium/connect:1.4
    bindings:
      - port: 8083
        containerPort: 8083
        protocol: http
    env:
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - BOOTSTRAP_SERVERS="kafka-broker-1:29092,kafka-broker-2:29094"
      - ZOOKEEPER_CONNECT="kafka-zookeeper:2181"
      - REST_PORT=8083
      - REST_HOST_NAME=kafka-connect
      - ADVERTISED_HOST_NAME=kafka-connect
      - LOG4J_ROOT_LOGLEVEL=INFO
      - LOG4J_LOGGERS="org.reflections=ERROR"
      - GROUP_ID="kafka-connect"

  - name: aggregatordb
    image: postgres:10.2
    tags:
      - postgres
    env:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrongPassw0rd
    bindings:
      - name: Connection
        port: 5432
        connectionString: Server=${host};Port=${port};Database=postgres;User Id=postgres;Password=YourStrongPassw0rd;Enlist=true;

  - name: flyway
    dockerFile: Docker/PostgresMigrations.Dockerfile
    dockerFileContext: .
    tags:
      - postgres
    env:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrongPassw0rd
      - POSTGRES_HOST=aggregatordb
      - POSTGRES_PORT=5432

  - name: configurator
    dockerFile: Docker/Configurator.Dockerfile
    dockerFileContext: .
    env:
      - SQL_SERVER_HOST=monolithicdb
      - SQL_SERVER_PORT=1433
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=YourStrongPassw0rd
      - SQL_SERVER_DATABASE=Inventory
      - SQL_SERVER_SERVER_NAME=dbServer
      - CDC_TABLES="dbo.Engines,dbo.Vehicles"
      - CONNECT_HOST=kafka-connect
      - CONNECT_PORT=8083
      - KAFKA_BOOTSTRAP_SERVERS="kafka-broker-1:29092,kafka-broker-2:29094"
      - KAFKA_HISTORY_TOPIC=my-connector-history